export const countries = [
  { name: 'Argentina' },
  { name: 'Australia' },
  { name: 'Bolivia' },
  { name: 'Brazil' },
  { name: 'Canada' },
  { name: 'Chile' },
  { name: 'China' },
  { name: 'Colombia' },
  { name: 'Costa Rica' },
  { name: 'Cuba' },
  { name: 'Dominican Republic' },
  { name: 'DR Congo' },
  { name: 'Ecuador' },
  { name: 'Egypt' },
  { name: 'El Salvador' },
  { name: 'Ethiopia' },
  { name: 'France' },
  { name: 'Germany' },
  { name: 'Guatemala' },
  { name: 'Honduras' },
  { name: 'India' },
  { name: 'Indonesia' },
  { name: 'Iran' },
  { name: 'Ireland' },
  { name: 'Italy' },
  { name: 'Jamaica' },
  { name: 'Japan' },
  { name: 'Kenya' },
  { name: 'Mexico' },
  { name: 'Morocco' },
  { name: 'Myanmar' },
  { name: 'Nepal' },
  { name: 'New Zealand' },
  { name: 'Nicaragua' },
  { name: 'Nigeria' },
  { name: 'Pakistan' },
  { name: 'Panama' },
  { name: 'Paraguay' },
  { name: 'Peru' },
  { name: 'Philippines' },
  { name: 'Russia' },
  { name: 'South Africa' },
  { name: 'South Korea' },
  { name: 'Spain' },
  { name: 'Thailand' },
  { name: 'Turkey' },
  { name: 'United Kingdom' },
  { name: 'United States' },
  { name: 'Uruguay' },
  { name: 'Venezuela' },
  { name: 'Vietnam' },
];

export const languages = [
  { key: 'es', langugage: 'Español (España)' },
  { key: 'en', langugage: 'Ingles (GB)' },
  { key: 'pr', langugage: 'Portuges (Portugal)' },
];
